chain:
  rpc: "https://rpc.laozi-testnet6.bandchain.org:443"
  chain_id: "band-laozi-testnet6"
  fee: "0.0025uband"
  timeout: "10s"
request:
  mnemonic: "smile stem oven genius cave resource better lunar nasty moon company ridge brass rather supply used horn three panic put venue analyst leader comic"
  oracle_script_id: 401
  calldata: "000000010000000342544303"
log_level: "info"
