name: Golangci-lint
on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20

      - name: golangci-lint (requester)
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54
          working-directory: requester
          args: --timeout=5m0s

      - name: golangci-lint (client)
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54
          working-directory: client
          args: --timeout=5m0s
